DROP TABLE IF EXISTS Page, User, Trace, IpAddressExclusion;

CREATE TABLE Page
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	DateCreation DATETIME NOT NULL,
	exclude TINYINT(1) NOT NULL DEFAULT 0,
	Page VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE User
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	DateCreation DATETIME NOT NULL,
	Name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE Trace
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Ip VARCHAR(45) NOT NULL,
	Host VARCHAR(255),
	DateCnx DATETIME NOT NULL,
	Id_User INT,
	Id_Page INT NOT NULL,
	FOREIGN KEY (Id_User) REFERENCES User(Id),
	FOREIGN KEY (Id_Page) REFERENCES Page(Id)
);

CREATE TABLE IpAddressExclusion
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Ip VARCHAR(150) NOT NULL
);

INSERT INTO Page VALUES (1, "1776-7-4 04:13:54", 0, "www.test.com");
INSERT INTO User VALUES (1, "1700-7-4 04:13:54", "Gerard");
INSERT INTO Trace VALUES (1, "192.05.35.68", "google", "1778-7-4 04:13:54", 1, 1);
INSERT INTO IpAddressExclusion VALUES (1, "234.21.05.2");
